---
- name: Deploy WordPress with Docker (Cloud-1)
  hosts: all
  become: yes
  gather_facts: yes
  
  pre_tasks:
    - name: Setup system packages
      include_tasks: playbooks/system-setup.yaml
      
    - name: Install Docker
      include_tasks: playbooks/docker-install.yaml
      
    - name: Create project folders
      include_tasks: playbooks/setup.yaml
      
    - name: Copy project files
      include_tasks: playbooks/copy-project.yaml
      
    
  roles:
    - mariadb
    - wordpress
    - nginx
    - phpmyadmin