---
- name: Deploy WordPress with Docker (Cloud-1)
  hosts: all
  become: yes
  gather_facts: yes
  
  tasks:
    - name: Setup system packages
      include_tasks: playbooks/system-setup.yaml
      
    - name: Install Docker
      include_tasks: playbooks/docker-install.yaml
      
    - name: Setup dynamic environment
      shell: ./setup-env.sh
      args:
        chdir: "{{ playbook_dir }}"
      become_user: "{{ ansible_env.USER }}"
      
    - name: Create project folders
      include_tasks: playbooks/setup.yaml
      
    - name: Copy project files
      include_tasks: playbooks/copy-project.yaml
      
    - name: Start WordPress project
      include_tasks: playbooks/run-project.yaml