---
- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /usr/share/keyrings/docker-archive-keyring.gpg
    mode: '0644'

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
    state: present

- name: Install Docker
  apt:
    name: docker-ce
    state: present
    update_cache: yes

- name: Create Docker plugins folder
  file:
    path: /usr/lib/docker/cli-plugins
    state: directory
    mode: '0755'

- name: Install Docker Compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64
    dest: /usr/lib/docker/cli-plugins/docker-compose
    mode: '0755'

- name: Start Docker service
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes