--- 



    
- name: Download Docker GPG key
  hosts: all
  become: yes
  tasks:
  - get_url:
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /usr/share/keyrings/docker-archive-keyring.gpg
      mode: '0644'
- name: Add Docker repository with signed-by option
  hosts: all
  become: yes
  tasks:
  - apt_repository:
      repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu jammy stable"
      state: present
      filename: docker
- name: Update apt and install docker-ce
  hosts: all
  become: yes
  tasks:
  - apt:
      name: docker-ce
      state: latest
      update_cache: true
- name: Ensure Docker CLI plugins directory exists
  hosts: all
  become: yes
  tasks:
  - file:
      path: /usr/lib/docker/cli-plugins
      state: directory
      mode: '0755'
- name: Install docker-compose plugin (Compose v2)
  hosts: all
  become: yes
  tasks:
  - get_url:
      url: https://github.com/docker/compose/releases/download/v2.29.2/docker-compose-linux-x86_64
      dest: /usr/lib/docker/cli-plugins/docker-compose
      mode: '0755'
- name: Enable and start Docker service
  hosts: all
  become: yes
  tasks:
  - systemd:
      name: docker
      enabled: yes
      state: started