---
- name: Run make command
  command: make
  args:
    chdir: "{{ ansible_env.HOME }}/inception"

- name: Start WordPress with Docker Compose
  command: docker compose up -d
  args:
    chdir: "{{ ansible_env.HOME }}/inception/srcs"
  become_user: "{{ ansible_env.USER }}"
