---
- name: Run make command
  command: make
  args:
    chdir: /home/anas/inception

- name: Start WordPress with Docker Compose
  command: docker compose up -d
  args:
    chdir: /home/anas/inception/srcs
  become_user: anas
