
#create Folder for the project and data for volumes

- name : create Folder for the project
  hosts: all
  become: yes
  tasks:
  - file:
      path: /home/anas/inception
      state: directory
      recurse: yes
- name : create Data for db
  hosts: all
  become: yes
  tasks:
  - file:
      path: /home/anas/data/mariadb
      state: directory
      recurse: yes
- name : create Data for wordpress
  hosts: all
  become: yes
  tasks:
  - file:
      path: /home/anas/data/wordpress
      state: directory
      recurse: yes