---
# Update and upgrade apt packages and install necessary packages
- name: update and upgrade apt packages

  hosts: all
  become: yes
  tasks:
    - apt:
        update_cache: yes
        upgrade: dist

- name: Install required system packages

  hosts: all
  become: yes
  tasks:
    - apt:
        pkg:
          - apt-transport-https
          - ca-certificates
          - curl
          - python3-pip
          - virtualenv
          - python3-setuptools
        state: latest
        update_cache: true
